let BrevoSdk, transactionalApi, apiInstance;

async function initBrevo() {
  if (transactionalApi) return true;
  if (!process.env.BREVO_API_KEY) return false;
  try {
    BrevoSdk = (await import('@getbrevo/brevo'));
    apiInstance = new BrevoSdk.TransactionalEmailsApi();
    apiInstance.authentications = { apiKey: { apiKey: process.env.BREVO_API_KEY } };
    transactionalApi = true;
    return true;
  } catch (err) {
    console.warn('[EmailService] Brevo init failed:', err.message);
    return false;
  }
}

function maskEmail(email) {
  if (!email || !email.includes('@')) return email || 'unknown';
  const [local, domain] = email.split('@');
  if (local.length <= 2) return `${local[0]}***@${domain}`;
  return `${local.slice(0, 2)}***${local.slice(-1)}@${domain}`;
}

export async function sendTestEmail({ recipientEmail, subject, body, senderName, approvalChecked }) {
  if (!approvalChecked) {
    return { success: false, error: 'Manual approval required. Check the approval checkbox before sending.', code: 'APPROVAL_REQUIRED' };
  }
  if (!recipientEmail || typeof recipientEmail !== 'string') {
    return { success: false, error: 'Recipient email is required', code: 'INVALID_EMAIL' };
  }
  if (recipientEmail.includes(',') || recipientEmail.includes(';')) {
    return { success: false, error: 'Only one recipient allowed in demo mode', code: 'MULTIPLE_RECIPIENTS' };
  }
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  if (!emailRegex.test(recipientEmail.trim())) {
    return { success: false, error: 'Invalid email format', code: 'INVALID_EMAIL' };
  }
  if (!subject || typeof subject !== 'string' || subject.trim().length === 0) {
    return { success: false, error: 'Subject is required', code: 'INVALID_SUBJECT' };
  }
  if (!body || typeof body !== 'string' || body.trim().length === 0) {
    return { success: false, error: 'Email body is required', code: 'INVALID_BODY' };
  }

  const hasSender = !!process.env.BREVO_SENDER_EMAIL;
  if (!hasSender) {
    return { success: false, error: 'Brevo sender email is not configured. Add BREVO_SENDER_EMAIL environment variable.', code: 'SENDER_NOT_CONFIGURED' };
  }
  const isReady = await initBrevo();
  if (!isReady) {
    return { success: false, error: 'Brevo API key is not configured or invalid. Add BREVO_API_KEY environment variable.', code: 'PROVIDER_NOT_CONFIGURED' };
  }

  const footer = '\n\n---\nThis is a manually approved test email generated by AI Marketing Platform.\nIf you received this in error, please disregard.';
  const fullBody = body.trim() + footer;

  try {
    const sendSmtpEmail = new BrevoSdk.SendSmtpEmail();
    sendSmtpEmail.subject = subject.trim();
    sendSmtpEmail.htmlContent = fullBody.replace(/\n/g, '<br/>');
    const senderEmail = process.env.BREVO_SENDER_EMAIL || 'noreply@ai-marketing-platform.com';
    sendSmtpEmail.sender = { name: senderName || 'AI Marketing Platform', email: senderEmail };
    sendSmtpEmail.to = [{ email: recipientEmail.trim(), name: '' }];
    sendSmtpEmail.replyTo = { email: senderEmail, name: senderName || 'AI Marketing Platform' };
    sendSmtpEmail.headers = { 'X-Entity-Ref-ID': 'ai-marketing-test-' + Date.now() };

    const result = await apiInstance.sendTransacEmail(sendSmtpEmail);
    const messageId = result?.body?.messageId || result?.body?.id || 'sent-' + Date.now();

    console.log('[EmailService] Email sent successfully:', { recipient: maskEmail(recipientEmail), messageId });

    return {
      success: true,
      provider: 'brevo',
      messageId,
      sentAt: new Date().toISOString(),
      recipient: maskEmail(recipientEmail),
      warnings: ['This is a test email. No campaign sequences were triggered.'],
    };
  } catch (error) {
    const safeMsg = error?.response?.body?.message || error?.message || 'Unknown email error';
    console.error('[EmailService] Send failed:', safeMsg);
    return {
      success: false,
      error: 'Email sending failed',
      details: safeMsg.includes('API key') ? 'Authentication failed. Check email provider configuration.' : safeMsg,
      code: 'SEND_FAILED',
    };
  }
}

export async function checkEmailProvider() {
  const hasKey = !!process.env.BREVO_API_KEY;
  const hasSender = !!process.env.BREVO_SENDER_EMAIL;
  if (!hasKey) return { configured: false, provider: null, reason: 'missing_api_key', senderConfigured: hasSender };
  if (!hasSender) return { configured: false, provider: null, reason: 'missing_sender_email', senderConfigured: false };
  const brevoOk = await initBrevo();
  return { configured: brevoOk, provider: brevoOk ? 'brevo' : null, reason: brevoOk ? 'configured' : 'init_failed', senderConfigured: hasSender };
}
