import { uploadBuffer } from './storage.service.js';

const REPLICATE_IMAGE_MODEL = process.env.REPLICATE_IMAGE_MODEL || 'black-forest-labs/flux-schnell';

function escapeXml(str) {
  if (!str) return '';
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&apos;');
}

async function generateWithReplicate(prompt, width, height) {
  try {
    const Replicate = (await import('replicate')).default;
    const replicate = new Replicate({ auth: process.env.REPLICATE_API_TOKEN });
    const input = { prompt, num_outputs: 1 };
    if (width && height) { input.width = width; input.height = height; }
    const output = await replicate.run(REPLICATE_IMAGE_MODEL, { input });
    const imageUrl = Array.isArray(output) ? output[0] : output;
    return { success: true, provider: 'replicate', imageUrl };
  } catch (err) {
    console.warn('[ImageService] Replicate failed:', err.message);
    return { success: false, error: err.message };
  }
}

async function generateWithHuggingFace(prompt) {
  try {
    const fetch = (await import('node-fetch')).default;
    const response = await fetch(
      'https://api-inference.huggingface.co/models/black-forest-labs/FLUX.1-dev',
      {
        headers: { Authorization: `Bearer ${process.env.HUGGINGFACE_API_KEY}` },
        method: 'POST',
        body: JSON.stringify({ inputs: prompt }),
      }
    );
    if (!response.ok) throw new Error(`HuggingFace returned ${response.status}`);
    const buffer = Buffer.from(await response.arrayBuffer());
    return { success: true, provider: 'huggingface', buffer };
  } catch (err) {
    console.warn('[ImageService] HuggingFace failed:', err.message);
    return { success: false, error: err.message };
  }
}

function generateSvgPoster({ prompt, headline, cta, platform, brandColors }) {
  const bgColor = brandColors?.[0] || '#2563eb';
  const accentColor = brandColors?.[1] || '#111827';
  const safeTitle = escapeXml(headline || 'AI Marketing Platform');
  const safeCta = escapeXml(cta || 'Learn More');
  const safePlatform = escapeXml(platform || 'Digital');
  const safePrompt = escapeXml(prompt ? (prompt.slice(0, 120) + (prompt.length > 120 ? '...' : '')) : '');

  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1080" viewBox="0 0 1080 1080">
  <defs>
    <linearGradient id="bg" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" style="stop-color:${bgColor};stop-opacity:1" />
      <stop offset="100%" style="stop-color:${accentColor};stop-opacity:1" />
    </linearGradient>
  </defs>
  <rect width="1080" height="1080" fill="url(#bg)" rx="20"/>
  <text x="540" y="300" text-anchor="middle" font-family="system-ui, sans-serif" font-size="64" font-weight="700" fill="white" letter-spacing="-1">${safeTitle}</text>
  <text x="540" y="400" text-anchor="middle" font-family="system-ui, sans-serif" font-size="28" fill="rgba(255,255,255,0.8)">${safePlatform.toUpperCase()}</text>
  <text x="540" y="550" text-anchor="middle" font-family="system-ui, sans-serif" font-size="32" fill="rgba(255,255,255,0.9)" font-style="italic">"${safePrompt}"</text>
  <rect x="390" y="680" width="300" height="70" rx="35" fill="white" opacity="0.9"/>
  <text x="540" y="728" text-anchor="middle" font-family="system-ui, sans-serif" font-size="24" font-weight="600" fill="${accentColor}">${safeCta}</text>
  <text x="540" y="960" text-anchor="middle" font-family="system-ui, sans-serif" font-size="18" fill="rgba(255,255,255,0.5)">Generated by AI Marketing Platform</text>
</svg>`;

  return Buffer.from(svg, 'utf-8');
}

function buildImagePrompt({ prompt, headline, cta, platform, brandColors }) {
  let finalPrompt = prompt;
  if (headline) finalPrompt += `, headline: "${headline}"`;
  if (cta) finalPrompt += `, call to action: "${cta}"`;
  if (platform) finalPrompt += `, optimized for ${platform}`;
  if (brandColors?.length) finalPrompt += `, brand colors: ${brandColors.join(', ')}`;
  finalPrompt += ', professional marketing poster design, clean modern style, high quality';
  return finalPrompt;
}

export async function generateImage({ prompt, headline, cta, platform, dimensions, brandColors }) {
  if (!prompt || typeof prompt !== 'string' || prompt.trim().length === 0) {
    return { success: false, error: 'Prompt is required' };
  }

  const finalPrompt = buildImagePrompt({ prompt, headline, cta, platform, brandColors });
  const dims = (dimensions || '1080x1080').split('x').map(Number);
  const width = dims[0] || 1080;
  const height = dims[1] || 1080;
  const warnings = [];
  let result;

  // Try Replicate first
  if (process.env.REPLICATE_API_TOKEN) {
    result = await generateWithReplicate(finalPrompt, width, height);
    if (result.success) {
      try {
        const fetch = (await import('node-fetch')).default;
        const imgResp = await fetch(result.imageUrl);
        const imgBuffer = Buffer.from(await imgResp.arrayBuffer());
        const storage = await uploadBuffer(imgBuffer, `poster-${Date.now()}.png`, 'posters', 'image');
        return {
          success: true, provider: 'replicate',
          imageUrl: storage.url, cloudinaryPublicId: storage.publicId,
          prompt: finalPrompt, generatedAt: new Date().toISOString(), warnings,
        };
      } catch (err) {
        warnings.push('Image generated but upload failed');
        return {
          success: true, provider: 'replicate',
          imageUrl: result.imageUrl, cloudinaryPublicId: null,
          prompt: finalPrompt, generatedAt: new Date().toISOString(), warnings,
        };
      }
    }
    warnings.push('Replicate image generation failed, trying HuggingFace');
  }

  // Try HuggingFace second
  if (process.env.HUGGINGFACE_API_KEY) {
    result = await generateWithHuggingFace(finalPrompt);
    if (result.success && result.buffer) {
      const storage = await uploadBuffer(result.buffer, `poster-${Date.now()}.png`, 'posters', 'image');
      return {
        success: true, provider: 'huggingface',
        imageUrl: storage.url, cloudinaryPublicId: storage.publicId,
        prompt: finalPrompt, generatedAt: new Date().toISOString(), warnings,
      };
    }
    warnings.push('HuggingFace image generation failed, using SVG fallback');
  }

  // Local SVG fallback
  warnings.push('Using local SVG poster fallback');
  const svgBuffer = generateSvgPoster({ prompt: finalPrompt, headline, cta, platform, brandColors });
  const storage = await uploadBuffer(svgBuffer, `poster-${Date.now()}.svg`, 'posters', 'image');

  return {
    success: true, provider: 'svg-fallback',
    imageUrl: storage.url, cloudinaryPublicId: storage.publicId,
    prompt: finalPrompt, generatedAt: new Date().toISOString(), warnings,
  };
}

export async function checkImageProviders() {
  return {
    huggingface: !!process.env.HUGGINGFACE_API_KEY,
    replicate: !!process.env.REPLICATE_API_TOKEN,
  };
}
