export interface CRMContact { id: string; firstName: string; lastName?: string; email?: string; phone?: string; jobTitle?: string; lifecycleStage: string; source?: string; consentStatus: string; ownerId?: string; status: string; companyId?: string; company?: CRMCompany; customFields?: any; archivedAt?: string; createdAt: string; }
export interface CRMCompany { id: string; name: string; website?: string; industry?: string; employeeRange?: string; location?: string; source?: string; contacts?: CRMContact[]; deals?: CRMDeal[]; archivedAt?: string; createdAt: string; }
export interface CRMDeal { id: string; name: string; description?: string; value?: number; currency?: string; status: string; stageId?: string; stage?: CRMPipelineStage; pipelineId?: string; pipeline?: CRMPipeline; contactId?: string; contact?: CRMContact; companyId?: string; company?: CRMCompany; campaignPlanId?: string; source?: string; ownerId?: string; expectedCloseDate?: string; }
export interface CRMPipeline { id: string; name: string; description?: string; status: string; stages: CRMPipelineStage[]; deals?: CRMDeal[]; }
export interface CRMPipelineStage { id: string; name: string; order: number; stageType?: string; isClosed: boolean; deals?: CRMDeal[]; }
export interface CRMTask { id: string; title: string; description?: string; priority: string; status: string; assignedTo?: string; contactId?: string; companyId?: string; dealId?: string; dueAt?: string; completedAt?: string; source?: string; createdAt: string; }
export interface CRMActivity { id: string; activityType: string; title: string; description?: string; activityDate: string; outcome?: string; source?: string; contactId?: string; companyId?: string; dealId?: string; }
export interface CRMWorkflow { id: string; name: string; description?: string; triggerType: string; triggerConfig?: any; conditions?: any; actions?: any; status: string; approvalStatus: string; versionNumber: number; }
export interface CRMWorkflowVersion { id: string; workflowId: string; versionNumber: number; snapshot: any; changeReason?: string; createdBy?: string; createdAt: string; }
export interface CRMWorkflowLog { id: string; workflowId: string; action: string; status?: string; message?: string; createdAt: string; }
export interface CRMImportJob { id: string; fileName: string; fileType: string; status: string; totalRows: number; validRows: number; invalidRows: number; importedRows: number; duplicateRows: number; columnMapping?: any; validationSummary?: any; errorDetails?: any; duplicateStrategy: string; }
