/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AppRouteImport } from './routes/app'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as ChatChatIdRouteImport } from './routes/chat.$chatId'
import { Route as AppSolutionGeneratorRouteImport } from './routes/app.solution-generator'
import { Route as AppSocialRouteImport } from './routes/app.social'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSeoRouteImport } from './routes/app.seo'
import { Route as AppRoiRouteImport } from './routes/app.roi'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppProductIntelligenceRouteImport } from './routes/app.product-intelligence'
import { Route as AppProductRouteImport } from './routes/app.product'
import { Route as AppPositioningRouteImport } from './routes/app.positioning'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppMarketRouteImport } from './routes/app.market'
import { Route as AppIntentRouteImport } from './routes/app.intent'
import { Route as AppGrowthWorkspaceRouteImport } from './routes/app.growth-workspace'
import { Route as AppContentRouteImport } from './routes/app.content'
import { Route as AppCompetitorsRouteImport } from './routes/app.competitors'
import { Route as AppCompetitorIntelligenceRouteImport } from './routes/app.competitor-intelligence'
import { Route as AppChatHistoryRouteImport } from './routes/app.chat-history'
import { Route as AppChannelsRouteImport } from './routes/app.channels'
import { Route as AppCampaignsRouteImport } from './routes/app.campaigns'
import { Route as AppCampaignIntelligenceRouteImport } from './routes/app.campaign-intelligence'
import { Route as AppAudienceRouteImport } from './routes/app.audience'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAgentsRouteImport } from './routes/app.agents'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ChatChatIdRoute = ChatChatIdRouteImport.update({
  id: '/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSolutionGeneratorRoute = AppSolutionGeneratorRouteImport.update({
  id: '/solution-generator',
  path: '/solution-generator',
  getParentRoute: () => AppRoute,
} as any)
const AppSocialRoute = AppSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSeoRoute = AppSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AppRoute,
} as any)
const AppRoiRoute = AppRoiRouteImport.update({
  id: '/roi',
  path: '/roi',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppProductIntelligenceRoute = AppProductIntelligenceRouteImport.update({
  id: '/product-intelligence',
  path: '/product-intelligence',
  getParentRoute: () => AppRoute,
} as any)
const AppProductRoute = AppProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => AppRoute,
} as any)
const AppPositioningRoute = AppPositioningRouteImport.update({
  id: '/positioning',
  path: '/positioning',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketRoute = AppMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AppRoute,
} as any)
const AppIntentRoute = AppIntentRouteImport.update({
  id: '/intent',
  path: '/intent',
  getParentRoute: () => AppRoute,
} as any)
const AppGrowthWorkspaceRoute = AppGrowthWorkspaceRouteImport.update({
  id: '/growth-workspace',
  path: '/growth-workspace',
  getParentRoute: () => AppRoute,
} as any)
const AppContentRoute = AppContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AppRoute,
} as any)
const AppCompetitorsRoute = AppCompetitorsRouteImport.update({
  id: '/competitors',
  path: '/competitors',
  getParentRoute: () => AppRoute,
} as any)
const AppCompetitorIntelligenceRoute =
  AppCompetitorIntelligenceRouteImport.update({
    id: '/competitor-intelligence',
    path: '/competitor-intelligence',
    getParentRoute: () => AppRoute,
  } as any)
const AppChatHistoryRoute = AppChatHistoryRouteImport.update({
  id: '/chat-history',
  path: '/chat-history',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsRoute = AppChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsRoute = AppCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignIntelligenceRoute = AppCampaignIntelligenceRouteImport.update({
  id: '/campaign-intelligence',
  path: '/campaign-intelligence',
  getParentRoute: () => AppRoute,
} as any)
const AppAudienceRoute = AppAudienceRouteImport.update({
  id: '/audience',
  path: '/audience',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/app': typeof AppRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/agents': typeof AppAgentsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/audience': typeof AppAudienceRoute
  '/app/campaign-intelligence': typeof AppCampaignIntelligenceRoute
  '/app/campaigns': typeof AppCampaignsRoute
  '/app/channels': typeof AppChannelsRoute
  '/app/chat-history': typeof AppChatHistoryRoute
  '/app/competitor-intelligence': typeof AppCompetitorIntelligenceRoute
  '/app/competitors': typeof AppCompetitorsRoute
  '/app/content': typeof AppContentRoute
  '/app/growth-workspace': typeof AppGrowthWorkspaceRoute
  '/app/intent': typeof AppIntentRoute
  '/app/market': typeof AppMarketRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/positioning': typeof AppPositioningRoute
  '/app/product': typeof AppProductRoute
  '/app/product-intelligence': typeof AppProductIntelligenceRoute
  '/app/profile': typeof AppProfileRoute
  '/app/roi': typeof AppRoiRoute
  '/app/seo': typeof AppSeoRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/social': typeof AppSocialRoute
  '/app/solution-generator': typeof AppSolutionGeneratorRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/agents': typeof AppAgentsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/audience': typeof AppAudienceRoute
  '/app/campaign-intelligence': typeof AppCampaignIntelligenceRoute
  '/app/campaigns': typeof AppCampaignsRoute
  '/app/channels': typeof AppChannelsRoute
  '/app/chat-history': typeof AppChatHistoryRoute
  '/app/competitor-intelligence': typeof AppCompetitorIntelligenceRoute
  '/app/competitors': typeof AppCompetitorsRoute
  '/app/content': typeof AppContentRoute
  '/app/growth-workspace': typeof AppGrowthWorkspaceRoute
  '/app/intent': typeof AppIntentRoute
  '/app/market': typeof AppMarketRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/positioning': typeof AppPositioningRoute
  '/app/product': typeof AppProductRoute
  '/app/product-intelligence': typeof AppProductIntelligenceRoute
  '/app/profile': typeof AppProfileRoute
  '/app/roi': typeof AppRoiRoute
  '/app/seo': typeof AppSeoRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/social': typeof AppSocialRoute
  '/app/solution-generator': typeof AppSolutionGeneratorRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/app': typeof AppRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/agents': typeof AppAgentsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/audience': typeof AppAudienceRoute
  '/app/campaign-intelligence': typeof AppCampaignIntelligenceRoute
  '/app/campaigns': typeof AppCampaignsRoute
  '/app/channels': typeof AppChannelsRoute
  '/app/chat-history': typeof AppChatHistoryRoute
  '/app/competitor-intelligence': typeof AppCompetitorIntelligenceRoute
  '/app/competitors': typeof AppCompetitorsRoute
  '/app/content': typeof AppContentRoute
  '/app/growth-workspace': typeof AppGrowthWorkspaceRoute
  '/app/intent': typeof AppIntentRoute
  '/app/market': typeof AppMarketRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/positioning': typeof AppPositioningRoute
  '/app/product': typeof AppProductRoute
  '/app/product-intelligence': typeof AppProductIntelligenceRoute
  '/app/profile': typeof AppProfileRoute
  '/app/roi': typeof AppRoiRoute
  '/app/seo': typeof AppSeoRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/social': typeof AppSocialRoute
  '/app/solution-generator': typeof AppSolutionGeneratorRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/app'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/app/agents'
    | '/app/analytics'
    | '/app/audience'
    | '/app/campaign-intelligence'
    | '/app/campaigns'
    | '/app/channels'
    | '/app/chat-history'
    | '/app/competitor-intelligence'
    | '/app/competitors'
    | '/app/content'
    | '/app/growth-workspace'
    | '/app/intent'
    | '/app/market'
    | '/app/notifications'
    | '/app/positioning'
    | '/app/product'
    | '/app/product-intelligence'
    | '/app/profile'
    | '/app/roi'
    | '/app/seo'
    | '/app/settings'
    | '/app/social'
    | '/app/solution-generator'
    | '/chat/$chatId'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/app/agents'
    | '/app/analytics'
    | '/app/audience'
    | '/app/campaign-intelligence'
    | '/app/campaigns'
    | '/app/channels'
    | '/app/chat-history'
    | '/app/competitor-intelligence'
    | '/app/competitors'
    | '/app/content'
    | '/app/growth-workspace'
    | '/app/intent'
    | '/app/market'
    | '/app/notifications'
    | '/app/positioning'
    | '/app/product'
    | '/app/product-intelligence'
    | '/app/profile'
    | '/app/roi'
    | '/app/seo'
    | '/app/settings'
    | '/app/social'
    | '/app/solution-generator'
    | '/chat/$chatId'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/app'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/app/agents'
    | '/app/analytics'
    | '/app/audience'
    | '/app/campaign-intelligence'
    | '/app/campaigns'
    | '/app/channels'
    | '/app/chat-history'
    | '/app/competitor-intelligence'
    | '/app/competitors'
    | '/app/content'
    | '/app/growth-workspace'
    | '/app/intent'
    | '/app/market'
    | '/app/notifications'
    | '/app/positioning'
    | '/app/product'
    | '/app/product-intelligence'
    | '/app/profile'
    | '/app/roi'
    | '/app/seo'
    | '/app/settings'
    | '/app/social'
    | '/app/solution-generator'
    | '/chat/$chatId'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  AppRoute: typeof AppRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ChatChatIdRoute: typeof ChatChatIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/chat/$chatId': {
      id: '/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof ChatChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/solution-generator': {
      id: '/app/solution-generator'
      path: '/solution-generator'
      fullPath: '/app/solution-generator'
      preLoaderRoute: typeof AppSolutionGeneratorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/social': {
      id: '/app/social'
      path: '/social'
      fullPath: '/app/social'
      preLoaderRoute: typeof AppSocialRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/seo': {
      id: '/app/seo'
      path: '/seo'
      fullPath: '/app/seo'
      preLoaderRoute: typeof AppSeoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/roi': {
      id: '/app/roi'
      path: '/roi'
      fullPath: '/app/roi'
      preLoaderRoute: typeof AppRoiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/product-intelligence': {
      id: '/app/product-intelligence'
      path: '/product-intelligence'
      fullPath: '/app/product-intelligence'
      preLoaderRoute: typeof AppProductIntelligenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/product': {
      id: '/app/product'
      path: '/product'
      fullPath: '/app/product'
      preLoaderRoute: typeof AppProductRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/positioning': {
      id: '/app/positioning'
      path: '/positioning'
      fullPath: '/app/positioning'
      preLoaderRoute: typeof AppPositioningRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/market': {
      id: '/app/market'
      path: '/market'
      fullPath: '/app/market'
      preLoaderRoute: typeof AppMarketRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/intent': {
      id: '/app/intent'
      path: '/intent'
      fullPath: '/app/intent'
      preLoaderRoute: typeof AppIntentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/growth-workspace': {
      id: '/app/growth-workspace'
      path: '/growth-workspace'
      fullPath: '/app/growth-workspace'
      preLoaderRoute: typeof AppGrowthWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/content': {
      id: '/app/content'
      path: '/content'
      fullPath: '/app/content'
      preLoaderRoute: typeof AppContentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/competitors': {
      id: '/app/competitors'
      path: '/competitors'
      fullPath: '/app/competitors'
      preLoaderRoute: typeof AppCompetitorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/competitor-intelligence': {
      id: '/app/competitor-intelligence'
      path: '/competitor-intelligence'
      fullPath: '/app/competitor-intelligence'
      preLoaderRoute: typeof AppCompetitorIntelligenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat-history': {
      id: '/app/chat-history'
      path: '/chat-history'
      fullPath: '/app/chat-history'
      preLoaderRoute: typeof AppChatHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/channels': {
      id: '/app/channels'
      path: '/channels'
      fullPath: '/app/channels'
      preLoaderRoute: typeof AppChannelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/campaigns': {
      id: '/app/campaigns'
      path: '/campaigns'
      fullPath: '/app/campaigns'
      preLoaderRoute: typeof AppCampaignsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/campaign-intelligence': {
      id: '/app/campaign-intelligence'
      path: '/campaign-intelligence'
      fullPath: '/app/campaign-intelligence'
      preLoaderRoute: typeof AppCampaignIntelligenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audience': {
      id: '/app/audience'
      path: '/audience'
      fullPath: '/app/audience'
      preLoaderRoute: typeof AppAudienceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agents': {
      id: '/app/agents'
      path: '/agents'
      fullPath: '/app/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAgentsRoute: typeof AppAgentsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAudienceRoute: typeof AppAudienceRoute
  AppCampaignIntelligenceRoute: typeof AppCampaignIntelligenceRoute
  AppCampaignsRoute: typeof AppCampaignsRoute
  AppChannelsRoute: typeof AppChannelsRoute
  AppChatHistoryRoute: typeof AppChatHistoryRoute
  AppCompetitorIntelligenceRoute: typeof AppCompetitorIntelligenceRoute
  AppCompetitorsRoute: typeof AppCompetitorsRoute
  AppContentRoute: typeof AppContentRoute
  AppGrowthWorkspaceRoute: typeof AppGrowthWorkspaceRoute
  AppIntentRoute: typeof AppIntentRoute
  AppMarketRoute: typeof AppMarketRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPositioningRoute: typeof AppPositioningRoute
  AppProductRoute: typeof AppProductRoute
  AppProductIntelligenceRoute: typeof AppProductIntelligenceRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRoiRoute: typeof AppRoiRoute
  AppSeoRoute: typeof AppSeoRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSocialRoute: typeof AppSocialRoute
  AppSolutionGeneratorRoute: typeof AppSolutionGeneratorRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentsRoute: AppAgentsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAudienceRoute: AppAudienceRoute,
  AppCampaignIntelligenceRoute: AppCampaignIntelligenceRoute,
  AppCampaignsRoute: AppCampaignsRoute,
  AppChannelsRoute: AppChannelsRoute,
  AppChatHistoryRoute: AppChatHistoryRoute,
  AppCompetitorIntelligenceRoute: AppCompetitorIntelligenceRoute,
  AppCompetitorsRoute: AppCompetitorsRoute,
  AppContentRoute: AppContentRoute,
  AppGrowthWorkspaceRoute: AppGrowthWorkspaceRoute,
  AppIntentRoute: AppIntentRoute,
  AppMarketRoute: AppMarketRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPositioningRoute: AppPositioningRoute,
  AppProductRoute: AppProductRoute,
  AppProductIntelligenceRoute: AppProductIntelligenceRoute,
  AppProfileRoute: AppProfileRoute,
  AppRoiRoute: AppRoiRoute,
  AppSeoRoute: AppSeoRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSocialRoute: AppSocialRoute,
  AppSolutionGeneratorRoute: AppSolutionGeneratorRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  AppRoute: AppRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ChatChatIdRoute: ChatChatIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
