import { getLatestEvidenceSnapshot } from '../../modules/evidence/evidence.service.js';
import { getSeoIntelligenceForChat } from "../loaders/seo-intelligence.loader.js";
import { getProductIntelligenceForChat } from "../loaders/product-intelligence.loader.js";
import { resolveProductIdentity } from '../resolvers/product-identity.resolver.js';
import { normalizeSeoForExecution } from "../normalizers/seo-intelligence.normalizer.js";
import { normalizeProductForContentStudio } from "../normalizers/product-intelligence.normalizer.js";
import { asArray, takeArray } from "../normalizers/array-helpers.js";

export async function buildEvidenceGraph(prisma, userId, chatId) {
  if (!prisma || !userId || !chatId) {
    throw new Error('prisma, userId, and chatId required');
  }

  const chat = await prisma.chat.findUnique({ where: { id: chatId } });
  if (!chat || chat.userId !== userId) {
    return { rejected: true, reason: 'Chat not found or owner mismatch', code: 'CHAT_ERROR' };
  }

  const evidenceSnapshot = await getLatestEvidenceSnapshot({ prisma, userId, chatId });
  const raw = evidenceSnapshot?.evidence || {};
  const website = raw.website || {};

  const [productIntel, competitorIntel, campaignIntel, seoIntel] = await Promise.all([
    getProductIntelligenceForChat({ prisma, userId, chatId }),
    prisma.competitorIntelligence.findFirst({ where: { chatId, userId } }).catch(() => null),
    prisma.campaignIntelligence.findFirst({ where: { chatId, userId } }).catch(() => null),
    getSeoIntelligenceForChat({ prisma, userId, chatId }),
  ]);

  const productAnalysis = productIntel?.productAnalysis || {};
  const audienceData = productIntel?.audienceIntelligence || {};
  const competitorData = competitorIntel?.competitorAnalysis || {};
  const campaignData = campaignIntel?.campaignGenerator || {};
  const channelData = campaignIntel?.channelRecommendation || {};

  const productIdentity = resolveProductIdentity({ chat, productIntelligence: productIntel, evidenceSnapshot, website });
  const normalizedSeo = normalizeSeoForExecution(seoIntel);
  const normalizedProduct = normalizeProductForContentStudio(productIntel, { website, usp: productAnalysis.usp, summary: productAnalysis.summary || productAnalysis.productSummary });

  const LOW_QUALITY_KEYWORDS = new Set([
    'started', 'alerts', 'outlier', 'shorts', 'text', 'tracking', 'trends',
    'content', 'alert', 'product', 'home', 'page', 'app', 'get', 'use',
    'how', 'what', 'why', 'when', 'where', 'login', 'signup', 'sign up',
    'register', 'pricing', 'features', 'blog', 'docs', 'documentation',
    'support', 'contact', 'about', 'careers', 'help', 'search', 'setting',
    'settings', 'dashboard', 'profile', 'account', 'billing',
  ]);

  const filteredKeywords = normalizedSeo.keywords.filter(k => {
    const kw = (typeof k === 'string' ? k : (k.keyword || k.phrase || k.text || '')).trim().toLowerCase();
    if (!kw || kw.length < 3) return false;
    if (LOW_QUALITY_KEYWORDS.has(kw)) return false;
    if (/^\d+$/.test(kw)) return false;
    if (kw.startsWith('http') || kw.startsWith('www')) return false;
    return true;
  });

  const autoGeneratedTopics = [];
  if (filteredKeywords.length > 0 && normalizedSeo.contentGaps.length === 0 && normalizedSeo.blogIdeas.length === 0) {
    const keywordTexts = filteredKeywords.slice(0, 10).map(k => typeof k === 'string' ? k : k.keyword).filter(Boolean);
    for (const kw of keywordTexts) {
      autoGeneratedTopics.push({ topic: `What is ${kw}? A Complete Guide`, contentType: 'faq_page', reason: 'Auto-generated from keyword' });
      autoGeneratedTopics.push({ topic: `${kw}: Benefits, Features, and Best Practices`, contentType: 'blog_article', reason: 'Auto-generated from keyword' });
      autoGeneratedTopics.push({ topic: `Top ${kw} Solutions Compared`, contentType: 'comparison_page', reason: 'Auto-generated from keyword' });
    }
  }

  const evidenceGraph = {
    _graphId: `graph_${chatId}_${Date.now()}`,
    _builtAt: new Date().toISOString(),
    chatId,
    userId,
    rejected: false,

    sources: {
      chat: true,
      evidenceSnapshot: Boolean(evidenceSnapshot),
      productIntelligence: Boolean(productIntel),
      competitorIntelligence: Boolean(competitorIntel),
      campaignIntelligence: Boolean(campaignIntel),
      seoIntelligence: Boolean(seoIntel),
    },

    company: {
      name: productIdentity.companyName || chat.title || null,
      productName: productIdentity.productName,
      brandName: productIdentity.brandName,
      websiteUrl: productIdentity.websiteUrl || null,
      domain: productIdentity.domain || null,
      industry: productAnalysis.industry || null,
    },

    product: {
      name: productIdentity.productName,
      brandName: productIdentity.brandName,
      summary: normalizedProduct.summary || productAnalysis.summary || productAnalysis.productSummary || null,
      description: productAnalysis.description || null,
      category: productAnalysis.category || null,
      features: normalizedProduct.features,
      benefits: normalizedProduct.benefits,
      useCases: normalizedProduct.useCases,
      integrations: normalizedProduct.integrations,
      pricing: normalizedProduct.pricing,
      capabilities: normalizedProduct.capabilities,
      usp: normalizedProduct.usp || productAnalysis.usp || null,
      differentiators: takeArray(productAnalysis.differentiators || productAnalysis.keyDifferentiators, 10),
    },

    website: {
      title: website.title || null,
      metaDescription: website.metaDescription || null,
      heroText: website.heroText || null,
      ctaTexts: takeArray(website.ctaTexts, 5),
      technologyHints: takeArray(website.technologyHints, 10),
      technologyStack: productAnalysis.technologyStack || null,
    },

    audience: {
      primary: audienceData.primaryAudience || null,
      personas: takeArray(audienceData.buyerPersonas, 5).map(p => ({
        name: p.name || p.title || null,
        role: p.role || null,
        painPoints: takeArray(p.painPoints, 5),
        goals: takeArray(p.goals, 5),
      })),
      painPoints: takeArray(
        normalizedProduct.painPoints.length > 0 ? normalizedProduct.painPoints : audienceData.painPoints,
        10
      ),
      industries: normalizedProduct.industries,
      targetAudience: normalizedProduct.targetAudience,
      customerSegments: normalizedProduct.targetAudience.length > 0 ? normalizedProduct.targetAudience : productAnalysis.customerSegments || [],
    },

    competitors: {
      list: takeArray(competitorData.competitors || competitorData.directCompetitors, 10).map(c => ({
        name: c.name || c.url || null,
        domain: c.domain || c.url || null,
        strengths: takeArray(c.strengths, 5),
        weaknesses: takeArray(c.weaknesses, 5),
      })),
      strengths: takeArray(competitorData.strengths, 5),
      weaknesses: takeArray(competitorData.weaknesses, 5),
      positioning: competitorIntel?.positioningEngine || null,
    },

    campaign: {
      goals: takeArray(campaignData.goals || campaignData.campaignGoals, 5),
      channels: channelData?.recommendedChannels?.length
        ? channelData.recommendedChannels.map((ch, i) => ({
            channel: ch.channel || ch.name,
            priority: ch.priority || 'medium',
            reason: ch.reason || null,
          }))
        : [],
      creativeAngles: takeArray(campaignData.creativeAngles || campaignData.messagingPillars, 10),
      brandVoice: campaignData.brandVoice || productAnalysis.brandVoice || null,
      executiveStory: campaignIntel?.executiveStory || null,
      actionPlan: campaignIntel?.actionPlan || null,
    },

    seo: {
      keywords: filteredKeywords.slice(0, 30),
      primaryKeywords: normalizedSeo.primaryKeywords,
      secondaryKeywords: normalizedSeo.secondaryKeywords,
      longTailKeywords: normalizedSeo.longTailKeywords,
      questionKeywords: normalizedSeo.questionKeywords,
      competitorKeywords: normalizedSeo.competitorKeywords,
      contentGaps: normalizedSeo.contentGaps.slice(0, 10),
      topicIdeas: normalizedSeo.blogIdeas.slice(0, 10),
      blogIdeas: normalizedSeo.blogIdeas.slice(0, 10),
      technicalAudit: normalizedSeo.technicalAudit,
      seoScore: normalizedSeo.seoScore,
      autoGeneratedTopics: autoGeneratedTopics.slice(0, 20),
      clusters: seoIntel?.keywordIntelligence?.clusters || seoIntel?.keywordIntelligenceRecord?.clusters || null,
    },

    cta: takeArray(
      normalizedProduct.cta.length > 0 ? normalizedProduct.cta : website.ctaTexts,
      3
    ),

    market: {
      risks: productIntel?.marketDiscovery?.marketRisks || null,
      opportunities: productIntel?.marketDiscovery?.growthOpportunities || null,
    },

    evidenceSnapshot: evidenceSnapshot ? { id: evidenceSnapshot.id, exists: true } : { exists: false },

    confidence: {
      product: productAnalysis.confidenceScore || 0,
      seo: seoIntel?.scoreBreakdown?.overallScore || 0,
    },

    _productIdentity: productIdentity,
    _readiness: {
      ready: true,
      product: Boolean(productIntel),
      audience: Boolean(audienceData?.primaryAudience || audienceData?.buyerPersonas?.length),
      competitor: Boolean(competitorIntel),
      campaign: Boolean(campaignIntel),
      seo: Boolean(seoIntel),
      hasKeywords: filteredKeywords.length > 0,
      hasFeatures: normalizedProduct.features.length > 0,
    },
    _warnings: [],
    _limitations: [],
  };

  if (!evidenceGraph.product.usp) evidenceGraph._limitations.push('No verified USP available');
  if (!evidenceGraph.product.features.length) evidenceGraph._limitations.push('No product features extracted');
  if (!evidenceGraph.audience.personas.length) evidenceGraph._warnings.push('No buyer personas defined');
  if (!evidenceGraph.audience.painPoints.length) evidenceGraph._warnings.push('No audience pain points');
  if (!evidenceGraph.competitors.list.length) evidenceGraph._warnings.push('No validated competitors');
  if (!evidenceGraph.seo.keywords.length) evidenceGraph._warnings.push('No keyword data available');

  return evidenceGraph;
}

export default { buildEvidenceGraph };
